### ISSUE TITLE
График выхода нового перевода

### ISSUE THREAD

**Issue by Jack1425** [missing-semester-rus/missing-semester-rus.github.io#1]
Планируете ли вы и дальше переводить, и если да, то с какой периодичностью?
И вопрос по субтитрам на ютубе, это ваша работа и будут ли они к другим частям?

**Comment by missing-semester-rus** [comment]
@Jack1425 субтитры не мои, автора, к сожалению, не знаю. 
планирую публиковать переводы новых лекций раз в неделю. но возможны сдвиги в сроках, т.к. пока перевожу в одиночку.
